# Constants for the Reddit CookUnity Monitor app

# Image URLs
cu_image_url = "https://i.imgur.com/tnwmOZN.png"
reddit_image_url = "https://images.squarespace-cdn.com/content/v1/5c5554d316b64061c6f8a20d/1630949829757-WXNOUZ8R4QQCXMIY4YMG/What-Is-The-Reddit-Logo-Called.png?format=2500w"

# Common negative words for sentiment analysis
NEGATIVE_WORDS = [
    "bad",
    "terrible",
    "awful",
    "horrible",
    "disappointing",
    "disappointed",
    "poor",
    "worst",
    "disgusting",
    "nasty",
    "gross",
    "tasteless",
    "bland",
    "expensive",
    "overpriced",
    "complaint",
    "issue",
    "problem",
    "wrong",
    "waste",
    "unhappy",
    "unhealthy",
    "cancel",
    "canceled",
    "cancellation",
    "unappetizing",
    "cold",
    "late",
    "delay",
    "refund",
    "money",
    "error",
    "complaint",
    "missing",
    "missing",
    "damaged",
    "soggy",
    "stale",
    "moldy",
    "spoiled",
    "rotten",
    "undercooked",
    "overcooked",
    "burnt",
    "burned",
    "customer service",
    "not worth",
    "never again",
    "rip-off",
    "ripoff",
    "rip off",
    "scam",
    "fraudulent",
]
